version: '3.8'
services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-api
    tty: true
    restart: always
    environment:
      - TZ:Asia/Tokyo
      - DEBUG=app:*
    ports:
      - '3000:3000'
    volumes:
      # バインドマウント
      - ./app:/app
    # 起動時のカレントフォルダを指定
    working_dir: /app
    # 起動後に実行するコマンドを指定
    command: npm start
